### PR TITLE
Add cps button iteration 3

### PR DESCRIPTION
**Pull request by hdoupe**

### CODE REVIEW

**Comment by hdoupe** [comment]
@GoFroggyRun I think this solves our problem

**Comment by GoFroggyRun** [comment]
Awesome! Thanks @andersonfrailey. 

I'm not able to test the backend locally though, due to weird dependency/package errors. @hdoupe does the CPS button work properly on your local?

**Comment by hdoupe** [comment]
@GoFroggyRun Everything is looking good on my end. This should be enough to allow you to begin work on graying out the parameters. I'll get to work on OpenSourcePolicyCenter/PolicyBrain#832

**Comment by GoFroggyRun** [comment]
@hdoupe thanks for updating the database. Do you think it makes more sense to have gray-out logic in a separate PR?

**Comment by hdoupe** [comment]
No problem. Yes, I think that's a good idea. I still need to do a little work on the flask/celery end. So, it would be good to have these changes merged.

**Pull request merged**
